# Generated by Django 6.0.5 on 2026-05-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('profiles', '0003_alter_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='section',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicclass'),
        ),
    ]
