# Generated by Django 6.0.5 on 2026-05-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('profiles', '0004_remove_studentprofile_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicclass'),
        ),
    ]
