"""
Django settings for educore project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'accounts.User'

# Application definition


from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "EduCore Admin",
    "SITE_HEADER": "EduCore",
    "SITE_SUBHEADER": "School Management System",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("img/logo-light.png"),
        "dark":  lambda request: static("img/logo-dark.png"),
    },
    "SITE_SYMBOL": "school",           # Material Symbol icon name
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "educore.settings.environment_callback",  # see below
    "DASHBOARD_CALLBACK": "educore.views.dashboard_callback",
    "THEME": "dark",                   # "light" | "dark" | None (user picks)
    "LOGIN": {
        "image": lambda request: static("img/login-bg.jpg"),
        "redirect_after": lambda request: reverse_lazy("admin:index"),
    },
    "STYLES": [
        lambda request: static("css/admin-custom.css"),
    ],
    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark":  "156 163 175",
            "default-light": "75 85 99",
            "default-dark":  "209 213 219",
            "important-light": "17 24 39",
            "important-dark":  "243 244 246",
        },
        "primary": {
            "50":  "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110",
            "950": "8 47 73",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {},
        },
    },
    
    "SIDEBAR": {
    "show_search": True,
    "show_all_applications": False,
    "navigation": [
        {
            "title": "Navigation",
            "separator": True,
            "collapsible": False,
            "items": [
                {
                    "title": "Dashboard",
                    "icon": "dashboard",
                    "link": reverse_lazy("admin:index"),
                },
            ],
        },
        {
            "title": "Accounts & Auth",
            "separator": True,
            "collapsible": True,
            "items": [
                {
                    "title": "Users",
                    "icon": "person",
                    "link": reverse_lazy("admin:accounts_user_changelist"),
                },
                {
                    "title": "Groups",
                    "icon": "group",
                    "link": reverse_lazy("admin:auth_group_changelist"),
                },
            ],
        },
        {
            "title": "Academics",
            "separator": True,
            "collapsible": True,
            "items": [
                {
                    "title": "Classes",
                    "icon": "class",
                    "link": reverse_lazy("admin:academics_academicclass_changelist"),       # ← AcademicClass model
                },
                {
                    "title": "Teacher assignments",
                    "icon": "assignment_ind",
                    "link": reverse_lazy("admin:academics_teacherclassassignment_changelist"),  # ← TeacherClassAssignment model
                },
            ],
        },
        {
            "title": "Profiles",
            "separator": True,
            "collapsible": True,
            "items": [
                {
                    "title": "Principal profile",
                    "icon": "manage_accounts",
                    "link": reverse_lazy("admin:profiles_principalprofile_changelist"),
                },
                {
                    "title": "Student profiles",
                    "icon": "school",
                    "link": reverse_lazy("admin:profiles_studentprofile_changelist"),
                },
                {
                    "title": "Teacher profiles",
                    "icon": "badge",
                    "link": reverse_lazy("admin:profiles_teacherprofile_changelist"),
                },
            ],
        },
        {
            "title": "Attendance",
            "separator": True,
            "collapsible": True,
            "items": [
                {
                    "title": "Attendance records",
                    "icon": "fact_check",
                    "link": reverse_lazy("admin:attendance_attendance_changelist"),
                },
            ],
        },
        {
            "title": "Library",
            "separator": True,
            "collapsible": True,
            "items": [
                {
                    "title": "Books",
                    "icon": "auto_stories",
                    "link": reverse_lazy("admin:library_book_changelist"),
                },
                {
                    "title": "Book issues",
                    "icon": "book_online",
                    "link": reverse_lazy("admin:library_bookissue_changelist"),
                },
            ],
        },
    ],
},
    
    
    
    
    
}

def environment_callback(request):
    return ["Production", "danger"]   # ["Development", "info"] for dev

INSTALLED_APPS = [
     # Unfold must come BEFORE django.contrib.admin
    "unfold",
    "unfold.contrib.filters",        # optional: advanced filters
    "unfold.contrib.forms",          # optional: styled forms
    "unfold.contrib.inlines",        # optional: sortable inlines
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'rest_framework',
    'academics',
    'profiles',
    'drf_spectacular',
    'attendance',
    'library',
]


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('JWT_ACCESS_MINUTES'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('JWT_REFRESH_DAYS'))
    ),
    'AUTH_HEADER_TYPES': (
        os.getenv('JWT_AUTH_HEADER'),
    ),
}


SPECTACULAR_SETTINGS = {
    "TITLE": "EduCore API",
    "DESCRIPTION": "School Management System APIs",
    "VERSION": "1.0.0",

    # JWT support in Swagger
    "SECURITY": [{"bearerAuth": []}],

    "COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
}

REST_FRAMEWORK = {
    
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # 🔥 GLOBAL PROTECTION
    ),
     'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        
    #   Now in browser you’ll see:
    # ✔ full error details
    # ✔ validation errors clearly
    )
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'educore.urls'
DEBUG = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'educore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
