# Generated by Django 6.0.5 on 2026-05-09 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('profiles', '0005_alter_studentprofile_academic_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicclass')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
